// AUTO-GENERATED by content-pipeline/src/exportToApp.js — do not hand-edit.
// Regenerate with: node src/exportToApp.js  (from content-pipeline/)
import img0 from "../../assets/bookVocab/water_0.jpeg";
import img1 from "../../assets/bookVocab/smiles_1.jpeg";
import img2 from "../../assets/bookVocab/bed_2.jpeg";
import img3 from "../../assets/bookVocab/sings_3.jpeg";
import img4 from "../../assets/bookVocab/book_4.png";
import img5 from "../../assets/bookVocab/under_5.png";
import img6 from "../../assets/bookVocab/read_6.png";
import img7 from "../../assets/bookVocab/on_7.png";
import img8 from "../../assets/bookVocab/woman_8.png";
import img9 from "../../assets/bookVocab/girl_9.png";
import img10 from "../../assets/bookVocab/in_10.png";
import img11 from "../../assets/bookVocab/helps_11.png";
import img12 from "../../assets/bookVocab/looks_12.png";
import img13 from "../../assets/bookVocab/into_13.png";
import img14 from "../../assets/bookVocab/sleeps_14.png";
import img15 from "../../assets/bookVocab/moon_15.png";
import img16 from "../../assets/bookVocab/mother_16.png";
import img17 from "../../assets/bookVocab/goes_17.png";
import img18 from "../../assets/bookVocab/hand_18.png";
import img19 from "../../assets/bookVocab/inside_19.jpeg";
import img20 from "../../assets/bookVocab/house_20.jpeg";
import img21 from "../../assets/bookVocab/cat_21.jpeg";
import img22 from "../../assets/bookVocab/dog_22.jpeg";
import img23 from "../../assets/bookVocab/table_23.png";
import img24 from "../../assets/bookVocab/garden_24.png";
import img25 from "../../assets/bookVocab/hen_25.png";
import img26 from "../../assets/bookVocab/food_26.jpeg";
import img27 from "../../assets/bookVocab/family_27.jpeg";
import img28 from "../../assets/bookVocab/father_28.jpeg";
import img29 from "../../assets/bookVocab/went_29.jpeg";
import img30 from "../../assets/bookVocab/ate_30.jpeg";
import img31 from "../../assets/bookVocab/up_31.jpeg";
import img32 from "../../assets/bookVocab/looked_32.jpeg";
import img33 from "../../assets/bookVocab/gave_33.jpeg";
import img34 from "../../assets/bookVocab/eats_34.jpeg";
import img35 from "../../assets/bookVocab/cow_35.png";
import img36 from "../../assets/bookVocab/behind_36.png";
import img37 from "../../assets/bookVocab/banana_37.png";
import img38 from "../../assets/bookVocab/man_38.png";
import img39 from "../../assets/bookVocab/baby_39.png";
import img40 from "../../assets/bookVocab/near_40.png";
import img41 from "../../assets/bookVocab/door_41.png";
import img42 from "../../assets/bookVocab/car_42.png";
import img43 from "../../assets/bookVocab/bus_43.png";
import img44 from "../../assets/bookVocab/boat_44.png";

export const BOOK_VOCAB_ASSETS: Record<string, number> = {
  "water": img0,
  "the water": img0,
  "a water": img0,
  "smiles": img1,
  "the smiles": img1,
  "a smiles": img1,
  "bed": img2,
  "the bed": img2,
  "a bed": img2,
  "sings": img3,
  "the sings": img3,
  "a sings": img3,
  "book": img4,
  "the book": img4,
  "a book": img4,
  "under": img5,
  "the under": img5,
  "a under": img5,
  "an under": img5,
  "read": img6,
  "the read": img6,
  "a read": img6,
  "on": img7,
  "the on": img7,
  "a on": img7,
  "an on": img7,
  "woman": img8,
  "the woman": img8,
  "a woman": img8,
  "girl": img9,
  "the girl": img9,
  "a girl": img9,
  "in": img10,
  "the in": img10,
  "a in": img10,
  "an in": img10,
  "helps": img11,
  "the helps": img11,
  "a helps": img11,
  "looks": img12,
  "the looks": img12,
  "a looks": img12,
  "into": img13,
  "the into": img13,
  "a into": img13,
  "an into": img13,
  "sleeps": img14,
  "the sleeps": img14,
  "a sleeps": img14,
  "moon": img15,
  "the moon": img15,
  "a moon": img15,
  "mother": img16,
  "the mother": img16,
  "a mother": img16,
  "goes": img17,
  "the goes": img17,
  "a goes": img17,
  "hand": img18,
  "the hand": img18,
  "a hand": img18,
  "inside": img19,
  "the inside": img19,
  "a inside": img19,
  "an inside": img19,
  "house": img20,
  "the house": img20,
  "a house": img20,
  "cat": img21,
  "the cat": img21,
  "a cat": img21,
  "dog": img22,
  "the dog": img22,
  "a dog": img22,
  "table": img23,
  "the table": img23,
  "a table": img23,
  "garden": img24,
  "the garden": img24,
  "a garden": img24,
  "hen": img25,
  "the hen": img25,
  "a hen": img25,
  "food": img26,
  "the food": img26,
  "a food": img26,
  "family": img27,
  "the family": img27,
  "a family": img27,
  "father": img28,
  "the father": img28,
  "a father": img28,
  "went": img29,
  "the went": img29,
  "a went": img29,
  "ate": img30,
  "the ate": img30,
  "a ate": img30,
  "an ate": img30,
  "up": img31,
  "the up": img31,
  "a up": img31,
  "an up": img31,
  "looked": img32,
  "the looked": img32,
  "a looked": img32,
  "gave": img33,
  "the gave": img33,
  "a gave": img33,
  "eats": img34,
  "the eats": img34,
  "a eats": img34,
  "an eats": img34,
  "cow": img35,
  "the cow": img35,
  "a cow": img35,
  "behind": img36,
  "the behind": img36,
  "a behind": img36,
  "banana": img37,
  "the banana": img37,
  "a banana": img37,
  "man": img38,
  "the man": img38,
  "a man": img38,
  "baby": img39,
  "the baby": img39,
  "a baby": img39,
  "near": img40,
  "the near": img40,
  "a near": img40,
  "door": img41,
  "the door": img41,
  "a door": img41,
  "car": img42,
  "the car": img42,
  "a car": img42,
  "bus": img43,
  "the bus": img43,
  "a bus": img43,
  "boat": img44,
  "the boat": img44,
  "a boat": img44,
};
