// Copies approved-for-now draft entries into the Expo app as bundled assets +
// a generated lookup module, so the child-facing app can show a real book
// picture the instant a matching word is spoken — no network, no re-download.
//
// NOTE: this exports whatever is in draft-entries.json AS IS. There is still
// no Admin review screen in KiddoCare (see content-pipeline/README.md), so
// nothing here has had a human approval pass yet — flip that on before
// treating this as "published" content, if/when that screen exists.
import { readFile, writeFile, mkdir, copyFile } from "node:fs/promises";
import path from "node:path";

function arg(name, def) {
  const i = process.argv.indexOf(`--${name}`);
  return i >= 0 ? process.argv[i + 1] : def;
}

function safeVarName(word, i) {
  const base = word.replace(/[^a-zA-Z0-9]/g, "_").replace(/^(\d)/, "_$1");
  return `${base || "w"}_${i}`;
}

async function main() {
  const draftPath = arg("draft", "content-source/gdl/draft-entries.json");
  const appAssetsDir = arg("assets-out", "../frontend/assets/bookVocab");
  const moduleOut = arg("module-out", "../frontend/src/modules/bookVocab.generated.ts");
  const metaOut = arg("meta-out", "../frontend/src/modules/bookVocab.meta.json");

  const entries = JSON.parse(await readFile(draftPath, "utf8"));

  // one picture per phrase — first sighting wins (later duplicates skipped)
  const byPhrase = new Map();
  for (const e of entries) {
    if (!byPhrase.has(e.phrase)) byPhrase.set(e.phrase, e);
  }

  await mkdir(appAssetsDir, { recursive: true });

  const imports = [];
  const mapLines = [];
  const meta = {};
  let i = 0;

  for (const [phrase, e] of byPhrase) {
    const srcImg = path.join(path.dirname(draftPath), pathFromEntry(e));
    const ext = path.extname(srcImg) || ".jpg";
    const destName = `${safeVarName(phrase, i)}${ext}`;
    try {
      await copyFile(srcImg, path.join(appAssetsDir, destName));
    } catch {
      continue; // image missing on disk (shouldn't happen, but don't break the export)
    }
    const varName = `img${i}`;
    imports.push(`import ${varName} from "../../assets/bookVocab/${destName}";`);
    for (const trigger of e.triggers) {
      mapLines.push(`  ${JSON.stringify(trigger)}: ${varName},`);
    }
    meta[phrase] = { book: e.book, level: e.level, licenseRef: e.licenseRef, page: e.page };
    i++;
  }

  const moduleSrc = `// AUTO-GENERATED by content-pipeline/src/exportToApp.js — do not hand-edit.
// Regenerate with: node src/exportToApp.js  (from content-pipeline/)
${imports.join("\n")}

export const BOOK_VOCAB_ASSETS: Record<string, number> = {
${mapLines.join("\n")}
};
`;
  await writeFile(moduleOut, moduleSrc);
  await writeFile(metaOut, JSON.stringify(meta, null, 2));

  console.log(`Exported ${i} book pictures (${mapLines.length} trigger phrases) to:`);
  console.log(`  ${appAssetsDir}`);
  console.log(`  ${moduleOut}`);
  console.log(`  ${metaOut}`);
}

function pathFromEntry(e) {
  return e.imagePath; // "<book-slug>/images/<file>", relative to content-source/gdl/
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
